
bot_setting:
  token: 7988426542:AAEoxlI3HtI_hg7b4KzuZI1L47DgHmH1XNI
  file_path: /home/egor/programm/vessels_bot/images
  prediction_device: cuda:2

models:
  segmentation:
    _target_: histomark_lib.torch_lib.models.SMPModel
    encoder_weights: imagenet
    in_channels: 3
    model_name: segformer
    encoder_name: mit_b3
    classes: 2
    checkpoint_path: /home/egor/programm/histomark_new_template/histomark/logs/train/runs/2025-02-27_16-27-50/checkpoints/clear_model_epoch:029-val_loss:0.0160-val_fbeta:0.9861-val_IoU:0.9688-val_AucROC:0.9893.ckpt

  invasion:
    _target_: histomark_lib.torch_lib.models.SMPModel
    encoder_weights: imagenet
    in_channels: 3
    model_name: segformer
    encoder_name: timm-efficientnet-b3 
    classes: 1
    checkpoint_path: /home/egor/programm/histomark_new_template/histomark/logs/train/runs/2025-02-10_17-31-05/checkpoints/clear_model_epoch:021-val_loss:0.1564-val_fbeta:0.9112-val_IoU:0.8368-val_AucROC:0.9844.ckpt